version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - '8545:8545'
      - '127.0.0.1:9229:9229'
